name: Cypress Tests

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: magcho-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: build and run webapp
        run: |
          yarn install
          yarn build
          yarn start &

      - name: cypress test run
        run: yarn cypress:run

      - name: archive screenshots
        working-directory: cypress
        run: tar zcvf screenshots.tar.gz screenshots


      - name: upload files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cypress/screenshots.tar.gz
            cypress/videos/*
